// Global catalog data used by script.js
window.catalogProducts = [
  // New Era core items
  {
    id: 1,
    name: "New Era Wordmark Year of the Horse Black 9FORTY Adjustable Cap",
    brand: "New Era",
    category: "Headwear",
    type: "Cap",
    price: 2395,
    tag: "New",
    image: "IMG/NWElogo.png",
    images: ["IMG/NWElogo.png", "IMG/duomodel1.png"],
    sizes: ["One Size"],
    sku: "01095001",
    description: "New Era Wordmark Year of the Horse Black 9FORTY Adjustable Cap featuring premium construction and classic streetwear styling. Perfect for everyday wear and street style enthusiasts.",
  },
  {
    id: 2,
    name: "New Era Script Year of the Horse Walnut Skully Hat",
    brand: "New Era",
    category: "Headwear",
    type: "Cap",
    price: 2595,
    tag: "New",
    image: "IMG/NWElogo.png",
  },
  {
    id: 3,
    name: "New Era Poly Suede Black Fleece Pants",
    brand: "New Era",
    category: "Bottom",
    type: "Apparel",
    price: 5595,
    tag: "New",
    image: "IMG/ESNlogo.png",
    images: ["IMG/ESNlogo.png", "IMG/duomodel1.png", "IMG/model1.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    sku: "01095093",
    description: "New Era Poly Suede Black Fleece Pants with soft poly suede finish for premium comfort. Made in China from 95% polyester and 5% polyurethane for durable, flexible sportswear wear. Fleece-lined construction delivers warmth and all-day comfort. Easy to style with sports t shirt, coolera t shirt, or jersey shirt for casual sports attire. Versatile sportswear essential that pairs well with headwear, caps for men, and new era womens looks.",
  },
  {
    id: 4,
    name: "New Era Wordmark Tough Gear Pack Cordura 9FORTY Adjustable Cap",
    brand: "New Era",
    category: "Headwear",
    type: "Cap",
    price: 3095,
    tag: "Online Exclusive",
    image: "IMG/NWElogo.png",
  },
  {
    id: 5,
    name: "New Era Box Logo Metal Badge 9FORTY Adjustable Cap",
    brand: "New Era",
    category: "Headwear",
    type: "Cap",
    price: 2395,
    tag: "New",
    image: "IMG/NWElogo.png",
  },
  {
    id: 6,
    name: "New Era Logo White 3 Pack Ankle Socks",
    brand: "New Era",
    category: "Accessory",
    type: "Accessory",
    price: 895,
    tag: "Essentials",
    image: "IMG/NWElogo.png",
  },
  {
    id: 7,
    name: "New Era Wordmark Year of the Horse Walnut Drawstring Bag",
    brand: "New Era",
    category: "Accessory",
    type: "Accessory",
    price: 2095,
    tag: "New",
    image: "IMG/NWElogo.png",
  },

  // Essentials
  {
    id: 20,
    name: "Essentials Relaxed Fit Graphic T-Shirt",
    brand: "Essentials",
    category: "Top",
    type: "Apparel",
    price: 2895,
    tag: "Bestseller",
    image: "IMG/ESNlogo.png",
  },
  {
    id: 21,
    name: "Essentials Everyday Sweatshorts",
    brand: "Essentials",
    category: "Bottom",
    type: "Apparel",
    price: 3295,
    tag: "New",
    image: "IMG/ESNlogo.png",
  },
  {
    id: 22,
    name: "Essentials Heavyweight Jersey Longsleeve",
    brand: "Essentials",
    category: "Top",
    type: "Apparel",
    price: 3595,
    tag: "Bestseller",
    image: "IMG/ESNlogo.png",
  },

  // Nike
  {
    id: 30,
    name: "Nike Club Fleece Pullover Hoodie",
    brand: "Nike",
    category: "Top",
    type: "Apparel",
    price: 4495,
    tag: "Online Exclusive",
    image: "IMG/NKElogo.png",
  },
  {
    id: 31,
    name: "Nike Club Cargo Track Pants",
    brand: "Nike",
    category: "Bottom",
    type: "Apparel",
    price: 5095,
    tag: "New",
    image: "IMG/NKElogo.png",
  },

  // Stussy
  {
    id: 40,
    name: "Stussy Stock Logo Pigment Dyed Tee Black",
    brand: "Stussy",
    category: "Top",
    type: "Apparel",
    price: 3495,
    tag: "New",
    image: "IMG/STSlogo.jpg",
  },
  {
    id: 41,
    name: "Stussy International Work Gear Canvas Jacket",
    brand: "Stussy",
    category: "Top",
    type: "Apparel",
    price: 8995,
    tag: "Limited",
    image: "IMG/STSlogo.jpg",
  },
  {
    id: 42,
    name: "Stussy Script Logo Bucket Hat Natural",
    brand: "Stussy",
    category: "Headwear",
    type: "Cap",
    price: 3295,
    tag: "New",
    image: "IMG/STSlogo.jpg",
  },

  // Carhartt
  {
    id: 50,
    name: "Carhartt WIP OG Active Jacket Black",
    brand: "Carhartt",
    category: "Top",
    type: "Apparel",
    price: 9995,
    tag: "Iconic",
    image: "IMG/CRTlogo.png",
  },
  {
    id: 51,
    name: "Carhartt WIP Single Knee Rinse Wash Pants",
    brand: "Carhartt",
    category: "Bottom",
    type: "Apparel",
    price: 6495,
    tag: "New",
    image: "IMG/CRTlogo.png",
  },
  {
    id: 52,
    name: "Carhartt WIP Chase Beanie Hamilton Brown",
    brand: "Carhartt",
    category: "Headwear",
    type: "Cap",
    price: 1995,
    tag: "Essentials",
    image: "IMG/CRTlogo.png",
  },

  // Chrome Hearts
  {
    id: 60,
    name: "Chrome Hearts Cross Patch Trucker Cap Black",
    brand: "Chrome Hearts",
    category: "Headwear",
    type: "Cap",
    price: 12995,
    tag: "Exclusive",
    image: "IMG/CHRlogo.png",
  },
  {
    id: 61,
    name: "Chrome Hearts Horseshoe Logo Pocket Tee White",
    brand: "Chrome Hearts",
    category: "Top",
    type: "Apparel",
    price: 10995,
    tag: "New",
    image: "IMG/CHRlogo.png",
  },
  {
    id: 62,
    name: "Chrome Hearts Leather Cross Patch Sweatpants",
    brand: "Chrome Hearts",
    category: "Bottom",
    type: "Apparel",
    price: 15995,
    tag: "Limited",
    image: "IMG/CHRlogo.png",
  },
];

